### ISSUE TITLE
单词换行

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/daily#10]
https://www.cnblogs.com/qiao20/p/8607963.html
1.
word-break 当行尾放不下一个单词时，决定单词内部该怎么摆放。

break-all: 强行上，挤不下的话剩下的就换下一行显示呗。霸道型。

keep-all: 放不下我了，那我就另起一行展示，再放不下，我也不退缩。傲骄型。

2.
word-wrap 当行尾放不下时，决定单词内是否允许换行

normal: 单词太长，换行显示，再超过一行就溢出显示。

break-word: 当单词太长时，先尝试换行，换行后还是太长，单词内还可以换行。

**Comment by misslishan** [comment]
问个问题我的文本输入给我强行换行咋办

**Comment by xiaweiss** [comment]
css 有控制是否换行的样式，可以看看是否符合你的需求
https://www.w3school.com.cn/cssref/pr_text_white-space.asp
