### ISSUE TITLE
其实 Mac 上的每个菜单命令，都能自定义快捷键

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/daily#3]
原文地址：https://sspai.com/post/34527

解锁了 Mac 自定义快捷键的正确姿势，工作效率又可以提高啦

![FireShot Capture 009 - 其实 Mac 上的每个菜单命令，都能自定义快捷键 - 一日一技 ∙ Mac - 少数派 - sspai com](https://user-images.githubusercontent.com/17960084/57869305-59677e80-7837-11e9-97c0-bfddf5c84ad0.png)

**Comment by qinhunter** [comment]
good

**Comment by huting0211** [comment]
强悍，有效
